export const FETCH_MUSIC_LIST : string = 'FETCH_MUSIC_LIST';
export const FETCH_MUSIC_LIST_SUCCESS : string = 'FETCH_MUSIC_LIST_SUCCESS';
export const FETCH_MUSIC_LIST_FAILURE : string = 'FETCH_MUSIC_LIST_FAILURE';

export const FETCH_MUSIC_ELEMENT : string = 'FETCH_MUSIC_ELEMENT';
export const FETCH_MUSIC_ELEMENT_SUCCESS : string = 'FETCH_MUSIC_ELEMENT_SUCCESS';
export const FETCH_MUSIC_ELEMENT_FAILURE : string = 'FETCH_MUSIC_ELEMENT_FAILURE';
export const RESET_FETCH_MUSIC_ELEMENT : string = 'RESET_FETCH_MUSIC_ELEMENT';

export const CREATE_MUSIC_ELEMENT : string = 'CREATE_MUSIC_ELEMENT';
export const CREATE_MUSIC_ELEMENT_SUCCESS : string = 'CREATE_MUSIC_ELEMENT_SUCCESS';
export const CREATE_MUSIC_ELEMENT_FAILURE : string = 'CREATE_MUSIC_ELEMENT_FAILURE';

export const UPDATE_MUSIC_ELEMENT : string = 'UPDATE_MUSIC_ELEMENT';
export const UPDATE_MUSIC_ELEMENT_SUCCESS : string = 'UPDATE_MUSIC_ELEMENT_SUCCESS';
export const UPDATE_MUSIC_ELEMENT_FAILURE : string = 'UPDATE_UPDATE_MUSIC_ELEMENT';

export const RESET_SAVE_MUSIC_ELEMENT : string = 'RESET_SAVE_MUSIC_ELEMENT';