export const FETCH_PUBLISHER_LIST : string = 'FETCH_PUBLISHER_LIST';
export const FETCH_PUBLISHER_LIST_SUCCESS : string = 'FETCH_PUBLISHER_LIST_SUCCESS';
export const FETCH_PUBLISHER_LIST_FAILURE : string = 'FETCH_PUBLISHER_LIST_FAILURE';