# Generated by Django 2.1.2 on 2018-11-14 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='장르', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='노래 제목', max_length=100)),
                ('singer', models.CharField(default='가수', max_length=20)),
                ('year', models.IntegerField(default=1900)),
                ('genre', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='music.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='배급', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='music',
            name='publisher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='music.Publisher'),
        ),
    ]
